---
name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build DLL
        run: |
          cd c-blosc
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: c-blosc/build/blosc/Release/blosc.dll
          if-no-files-found: error
  release:
    if: startsWith(github.ref, 'refs/tags')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts from build
        uses: actions/download-artifact@v2
      - name: List artifacts
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/blosc.dll
